const destinations = [

    // ===== WATERFALLS (5) =====
    {
      id:"ingkumhan-falls",
      name:"Ingkumhan Falls",
      category:"waterfalls",
      municipality:"Dimiao",
      shortDescription:"A community-loved waterfall nestled in Dimiao's lush forest, perfect for a refreshing swim after a scenic hike.",
      fullDescription:"Ingkumhan Falls is a hidden gem nestled in the lush forests of Dimiao, Bohol. Cherished and well-maintained by the local community, it offers a refreshing natural pool after a scenic jungle hike. The falls cascade into a serene basin surrounded by dense tropical vegetation, creating a tranquil oasis for those seeking to connect with nature. The community's dedication to preserving this natural wonder ensures that it remains a pristine destination for both locals and travelers alike.",
      howToGetThere:"From Tagbilaran, drive to Dimiao (approximately 2 hours). From the town center, hire a tricycle to the trailhead (20 minutes). The hike to the falls takes about 30 minutes.",
      estimatedBudget:"₱1,000–₱2,500 per person",
      travelReminders:["Bring water and snacks for the hike","Wear sturdy, non-slip shoes","Hire a local guide for the trail"],
      sustainabilityNote:"This waterfall is loved and maintained by the local community. Please carry out all waste and avoid using soaps or shampoos in the natural pool.",

      image: "images/uploads/ing 3.jpg",
    },
    {
      id:"can-umantad-falls",
      name:"Can-umantad Falls",
      category:"waterfalls",
      municipality:"Candijay",
      shortDescription:"The highest waterfall in Bohol — a majestic 60-meter curtain of water plunging into a mist-filled jungle pool.",
      fullDescription:"Can-umantad Falls is the tallest waterfall in Bohol, standing at an impressive 60 meters. Located in the interior municipality of Candijay, this powerful cascade plunges into a natural pool surrounded by lush primary forest. The surrounding forest is home to diverse wildlife, and the sheer force of the water creates a refreshing mist that can be felt from meters away. Despite its grandeur, Can-umantad remains largely off the mainstream tourist trail — making it a truly rewarding discovery.",
      howToGetThere:"From Tagbilaran, take a bus or van to Candijay (1.5 to 2 hours). Register at the barangay hall and hire a local guide for the trek (approximately 30 minutes).",
      estimatedBudget:"₱400–₱1,200 per person",
      travelReminders:["Wear sturdy shoes — the trail can be slippery","Hire a local guide","Bring insect repellent and waterproof bags","Start early morning for the best experience"],
      sustainabilityNote:"Stay on marked trails to prevent erosion. Do not use soap or shampoo in the natural pool. This area is a protected watershed — follow all local regulations.",
      image: "images/uploads/can umantad.jpg",
    },
    {
      id:"busai-dream-falls",
      name:"Busai Dream Falls",
      category:"waterfalls",
      municipality:"Loboc",
      shortDescription:"A secluded jungle waterfall with a natural infinity pool — Loboc's best-kept secret for summer adventures.",
      fullDescription:"Busai Dream Falls is a secluded natural gem tucked away in the forests of Loboc, Bohol. The falls plunge into a stunning natural infinity pool surrounded by dense jungle canopy, offering a tranquil escape for adventurous visitors. Unlike other popular waterfalls in the region, Busai Dream sees far fewer crowds, giving you a more intimate and immersive experience with nature. It's the perfect spot for families and friend groups looking for a memorable summer dip.",
      howToGetThere:"From Tagbilaran, drive to Loboc (approximately 45 minutes). From the town center, hire a tricycle to the trailhead (15 minutes). The hike to the falls takes about 20 minutes through a well-marked trail.",
      estimatedBudget:"₱800–₱2,000 per person",
      travelReminders:["Stay well hydrated on the hike","Wear appropriate footwear","Bring insect repellent","Keep children supervised near the pool"],
      sustainabilityNote:"This area is a protected watershed. Follow all local regulations, do not litter, and avoid bringing single-use plastics.",
      image: "images/uploads/busai 2.jpg",
    },
    {
      id:"kawasan-falls-trinidad",
      name:"Kawasan Falls",
      category:"waterfalls",
      municipality:"Trinidad",
      shortDescription:"A stunning multi-tiered waterfall with emerald-green pools, perfect for swimming and cliff jumping.",
      fullDescription:"Kawasan Falls in Trinidad, Bohol is a breathtaking natural wonder featuring multi-tiered cascades flowing into brilliant emerald-green pools. The falls are embraced by lush vegetation and towering rock faces, creating an almost otherworldly atmosphere. Visitors can swim in the cool, clear water, enjoy cliff jumping from the rock ledges, or simply relax and soak in the natural beauty. The site also has small food stalls and rest areas, making it a great all-day destination.",
      howToGetThere:"From Tagbilaran, take a bus to Trinidad (approximately 1 hour). Ask locals to guide you to the falls from the town center.",
      estimatedBudget:"₱300–₱800 per person",
      travelReminders:["Check water conditions before jumping off ledges","Wear water shoes","Bring sun protection","Food stalls are available on-site"],
      sustainabilityNote:"Do not litter. Avoid using soaps in the natural pools, and respect the surrounding forest ecosystem.",
      image: "images/uploads/kaw 5.jpg",
    },
    {
      id:"malingin-falls",
      name:"Malingin Falls",
      category:"waterfalls",
      municipality:"Cortes",
      shortDescription:"A beautiful, serene waterfall with crystal-clear waters — Bohol's hidden romantic escape.",
      fullDescription:"Malingin Falls, located in Barangay Patrocinio, Cortes, Bohol, is a serene natural attraction surrounded by lush greenery. It features crystal-clear waters cascading down rocky cliffs into a refreshing pool below — ideal for swimming, picnicking, and photography. Away from the more crowded tourist spots, Malingin offers a peaceful retreat perfect for couples, families, and anyone seeking a quiet connection with nature.",
      howToGetThere:"From Tagbilaran City, take a bus to Cortes (approximately 1 hour). From Cortes, take a tricycle or habal-habal to Malingin (about 10 minutes).",
      estimatedBudget:"₱500–₱1,500 per person",
      travelReminders:["Bring your own food and water","Wear appropriate footwear for slippery rocks","Always practice water safety"],
      sustainabilityNote:"Please carry out all trash with you. Avoid disturbing the natural rock formations and surrounding flora along the trail.",
      image: "images/uploads/mal 1.jpg",
    },

    // ===== BEACHES (5) =====
    {
      id:"quinale-beach",
      name:"Quinale Beach",
      category:"beaches",
      municipality:"Anda",
      shortDescription:"A pristine white-sand beach with turquoise waters and swaying palms — Bohol's unspoiled paradise.",
      fullDescription:"Quinale Beach in Anda is one of Bohol's most pristine and least-commercialized beaches, offering powdery white sand and crystal-clear turquoise waters that stretch as far as the eye can see. Backed by towering coconut palms, this beach remains largely undeveloped, giving visitors a raw and authentic island experience. Whether you're swimming, snorkeling, or simply lounging by the shore, Quinale delivers a slice of paradise away from the typical tourist crowds.",
      howToGetThere:"From Tagbilaran, drive to Anda (approximately 2.5 hours). From the town proper, hire a tricycle or habal-habal to Quinale Beach (15 minutes).",
      estimatedBudget:"₱500–₱1,500 per person",
      travelReminders:["Bring your own food and drinks","Wear sun protection","Perfect for summer season and sunset watching","Snorkeling gear is recommended"],
      sustainabilityNote:"This beach is largely pristine — help keep it that way. Pack out all trash and avoid disturbing coral formations or marine life.",
      image:"images/uploads/quinale.jpg",
    },
    {
      id:"sibukaw-beach",
      name:"Sibukaw Beach",
      category:"beaches",
      municipality:"Anda",
      shortDescription:"A secluded shoreline of fine white sand and calm azure waters, perfect for solitude and sunsets.",
      fullDescription:"Sibukaw Beach is a quiet, hidden stretch of white sand in Anda, Bohol — the kind of place where you can hear the waves and little else. With calm, glassy waters and minimal foot traffic, it's ideal for those who want to disconnect and enjoy nature at its most peaceful. The beach is perfect for long walks along the shore, swimming in safe, shallow waters, and catching spectacular sunsets. An authentic Bohol experience for those willing to venture off the beaten path.",
      howToGetThere:"From Tagbilaran, drive to Anda (approximately 2.5 hours). Ask locals in Anda proper for directions to Sibukaw Beach — a short tricycle ride away.",
      estimatedBudget:"₱500–₱1,200 per person",
      travelReminders:["Bring all essentials as facilities are limited","Best visited on clear days","Ideal for solitude — great for solo travelers and couples"],
      sustainabilityNote:"Keep this hidden beach clean. Do not leave any waste behind and avoid collecting shells or disturbing wildlife.",
      image:"images/uploads/sibukaw.jpg",
    },
    {
      id:"doljo-beach",
      name:"Doljo Beach",
      category:"beaches",
      municipality:"Panglao",
      shortDescription:"A calm, palm-lined beach on Panglao's quieter side, beloved by divers and those seeking peaceful shores.",
      fullDescription:"Doljo Beach sits on the less-touristy northern coast of Panglao Island, offering a laid-back alternative to the busier Alona Beach. Known for its calm, shallow waters and excellent dive sites just offshore, Doljo is a favorite among diving enthusiasts and travelers who prefer a more relaxed beach atmosphere. Outrigger boats dot the shoreline, palm trees provide natural shade, and the overall vibe is unhurried and genuine — a true escape from the crowds.",
      howToGetThere:"From Tagbilaran Port, take a tricycle to Panglao (30 minutes). From Panglao town, hire a habal-habal to Doljo Beach (10 minutes).",
      estimatedBudget:"₱300–₱800 per person",
      travelReminders:["Great for snorkeling and diving","Bring sun protection","Tricycles and habal-habal are available for hire"],
      sustainabilityNote:"Use reef-safe sunscreen to protect the coral reef ecosystem. Do not step on or touch coral formations.",
      image:"images/uploads/doljo 1.PNG",
    },
    {
      id:"bikini-beach",
      name:"Bikini Beach",
      category:"beaches",
      municipality:"Panglao",
      shortDescription:"A vibrant aerial-view stunner with electric blue waters and lush green cliffs — Panglao's hidden coastal gem.",
      fullDescription:"Bikini Beach is one of Panglao's most visually striking beaches — best appreciated from above, where its crescent of white sand meets vivid turquoise and deep blue waters, framed by dense tropical greenery. Despite its beauty, it remains far less visited than nearby Alona Beach, offering a more exclusive and serene experience. The beach is great for swimming, snorkeling, and soaking up the scenery in a truly unspoiled coastal setting.",
      howToGetThere:"From Tagbilaran, take a tricycle or van to Panglao Island (30 minutes). From Panglao, hire a habal-habal to Bikini Beach — ask locals for directions.",
      estimatedBudget:"₱300–₱1,000 per person",
      travelReminders:["Wear reef-safe sunscreen","Snorkeling gear recommended","Facilities are limited — bring your own food and water"],
      sustainabilityNote:"The coral reef here is ecologically rich. Use only reef-safe sunscreen and avoid standing on or touching coral. Take all waste with you.",
      image:"images/uploads/bikini 5.PNG",
    },
    {
      id:"momo-beach",
      name:"Momo Beach",
      category:"beaches",
      municipality:"Panglao",
      shortDescription:"A pristine hidden beach on Panglao Island with crystal-clear waters and soft white sand.",
      fullDescription:"Momo Beach is a hidden gem on the island of Panglao, Bohol. This pristine stretch of coastline boasts crystal-clear turquoise waters and soft white sand, making it an ideal spot for swimming, sunbathing, and relaxing. Far less crowded than other popular Panglao beaches, Momo offers a more intimate and tranquil experience with nature. It's the kind of beach you'll want to keep secret — peaceful, beautiful, and completely unspoiled.",
      howToGetThere:"From Tagbilaran Port, head to Panglao Island by tricycle (30 minutes). From Panglao town proper, hire a habal-habal to Momo Beach.",
      estimatedBudget:"₱300–₱800 per person",
      travelReminders:["Bring your own food and water","Wear sun protection","Respect the quiet environment and local customs"],
      sustainabilityNote:"Please take all trash with you. Avoid disturbing natural coral formations along the shore and use reef-safe sunscreen.",
      image:"images/uploads/MOMO 2.PNG",
    },

    // ===== CULTURAL SITES (5) =====
    {
      id:"baclayon-ancestral-houses",
      name:"Baclayon Ancestral Houses",
      category:"cultural",
      municipality:"Baclayon",
      shortDescription:"Centuries-old colonial-era ancestral homes that whisper stories of Bohol's Spanish past.",
      fullDescription:"The ancestral houses of Baclayon are some of the finest surviving examples of Spanish colonial architecture in Bohol. These centuries-old structures, built from coral stone and hardwood, feature intricately carved facades, old capiz shell windows, and interiors filled with antique furnishings. Walking through Baclayon's heritage streets is like stepping into a living museum — every structure tells a story of the families, faith, and resilience that shaped Boholano identity across generations.",
      howToGetThere:"From Tagbilaran City, drive or take a tricycle to Baclayon (approximately 15–20 minutes). The ancestral houses are scattered near the town church and plaza.",
      estimatedBudget:"₱100–₱300 per person",
      travelReminders:["Ask permission before entering or photographing private properties","Best explored on foot","A local guide can enrich your visit with historical context"],
      sustainabilityNote:"These are fragile heritage structures. Do not touch, lean on, or deface any part of the buildings. Support local preservation efforts.",
      image:"images/uploads/baclayon an 1.jpg",
    },
    {
      id:"clarin-ancestral-house",
      name:"Clarin Ancestral House",
      category:"cultural",
      municipality:"Loay",
      shortDescription:"A remarkably preserved Spanish-era ancestral house that stands as a monument to Bohol's colonial heritage.",
      fullDescription:"The Clarin Ancestral House in Loay is one of Bohol's most iconic heritage structures, dating back to the Spanish colonial period. The two-story stone and hardwood house has survived centuries of typhoons, earthquakes, and time, its weathered facade a testament to the craftsmanship of its era. Its distinctive architectural style — combining Filipino and Spanish influences — makes it a fascinating subject for history lovers and photographers alike. The structure remains a proud symbol of Bohol's deep-rooted cultural heritage.",
      howToGetThere:"From Tagbilaran, drive to Loay (approximately 25–30 minutes). The ancestral house is located near the town center — ask any local for directions.",
      estimatedBudget:"₱100–₱300 per person",
      travelReminders:["Be respectful — this may still be a privately owned property","Best visited in the morning for good lighting","Hire a local heritage guide for context"],
      sustainabilityNote:"Do not touch the structure's walls or fixtures. Report any damage or vandalism to the local heritage office. Support preservation initiatives.",
      image:"images/uploads/clarin 1.jpg",
    },
    {
      id:"baclayon-church-museum",
      name:"Baclayon Church Museum",
      category:"cultural",
      municipality:"Baclayon",
      shortDescription:"One of the oldest churches in the Philippines, housing centuries of sacred artifacts and colonial religious heritage.",
      fullDescription:"The Baclayon Church, formally known as the Immaculate Conception Parish, is among the oldest stone churches in the Philippines — built by the Jesuits in 1595. Attached to the church is a museum housing a remarkable collection of religious artifacts, antique vestments, ancient liturgical items, and centuries-old manuscripts. The museum offers a rare window into Bohol's deep Catholic roots and the colonial history that shaped its spiritual identity. The interiors are atmospheric and evocative, with darkened wooden floors and walls lined with sacred relics.",
      howToGetThere:"From Tagbilaran City, drive or take a tricycle to Baclayon (approximately 15–20 minutes). The church and museum are at the town center.",
      estimatedBudget:"₱50–₱150 per person (museum entrance fee applies)",
      travelReminders:["Dress modestly — shoulders and knees covered","Photography restrictions apply inside the museum","Visit on weekday mornings to avoid crowds"],
      sustainabilityNote:"These are irreplaceable religious and cultural artifacts. Follow all museum guidelines and do not touch exhibits. Your entrance fee supports preservation.",
      image:"images/uploads/baclayon museum 4.jpg",
    },
    {
      id:"asin-tibuok",
      name:"Asin Tibuok",
      category:"cultural",
      municipality:"Alburquerque",
      shortDescription:"Bohol's ancient artisanal salt — a rare, smoke-infused delicacy crafted through a centuries-old tradition.",
      fullDescription:"Asin Tibuok (literally 'whole salt') is one of the rarest artisanal salts in the world, produced only in Alburquerque, Bohol. Made by burning coconut husks and filtering seawater through the ash, the brine is then slow-boiled in clay pots for days until it crystallizes into a hard, smoke-kissed salt ball. The process has been passed down through generations of Boholano families and is recognized as a cultural intangible heritage. Visitors can witness this extraordinary craft firsthand and purchase one of the world's most unique culinary treasures.",
      howToGetThere:"From Tagbilaran, drive to Alburquerque (approximately 25 minutes). Ask locals for the Asin Tibuok production site — the makers welcome visitors.",
      estimatedBudget:"₱100–₱500 per person",
      travelReminders:["The production process is seasonal — call ahead to confirm availability","Bring cash to purchase Asin Tibuok directly from producers","This makes for a unique pasalubong!"],
      sustainabilityNote:"Support the artisan families who keep this tradition alive by purchasing directly from them. Avoid resellers to ensure fair compensation for the makers.",
      image:"images/uploads/asin tibuokk.jpg",
    },
    {
      id:"punta-cruz-watchtower",
      name:"Punta Cruz Watchtower",
      category:"cultural",
      municipality:"Maribojoc",
      shortDescription:"A centuries-old Spanish watchtower perched on a rocky cliff — a sentinel overlooking the Bohol Strait.",
      fullDescription:"The Punta Cruz Watchtower in Maribojoc is one of Bohol's best-preserved Spanish-era defensive structures, built in the 17th century to guard against Moro pirate raids. Perched atop a rugged coastal cliff, the octagonal coral-stone tower commands sweeping views of the Bohol Strait and the surrounding coastline. The site is marked by a large wooden cross and a red-railing viewing area, and its windswept, dramatic setting makes it one of the most atmospheric heritage landmarks on the island.",
      howToGetThere:"From Tagbilaran, drive to Maribojoc (approximately 20–25 minutes). The watchtower is near the coast — follow signage from the town center.",
      estimatedBudget:"₱50–₱200 per person",
      travelReminders:["Great for sunrise and sunset visits","The coastal path can be uneven — wear sturdy shoes","Bring a camera — the views are spectacular"],
      sustainabilityNote:"This heritage structure is fragile. Do not climb on or deface the watchtower. Help preserve it for future generations by following all posted guidelines.",
      image:"images/uploads/punta 5.jpg",
    },

    // ===== HILLS (5) =====
    {
      id:"kankoka-hills",
      name:"Kankoka Hills",
      category:"hills",
      municipality:"Candijay",
      shortDescription:"A breathtaking hillside viewpoint in Candijay offering sweeping panoramas of Bohol's lush interior and rolling landscapes.",
      fullDescription:"Kankoka Hills in Candijay is one of Bohol's most rewarding off-the-beaten-path viewpoints, offering wide, unobstructed panoramas of the province's verdant rolling terrain. The trek up the hill winds through open grassland and scattered trees, rewarding visitors with a 360-degree view that stretches across valleys, forests, and distant barangays. Far from the tourist crowds, Kankoka Hills is a favorite among locals who come to catch stunning sunrises and sunsets. It is also a great spot for picnics, photography, and quiet reflection amid nature.",
      howToGetThere:"From Tagbilaran, take a bus or van to Candijay (approximately 1.5 to 2 hours). From the town center, ask locals or hire a habal-habal to Kankoka Hills.",
      estimatedBudget:"₱300–₱800 per person",
      travelReminders:["Best visited at sunrise or sunset for dramatic views","Wear comfortable walking shoes","Bring water and snacks","A local guide is recommended for first-time visitors"],
      sustainabilityNote:"Stay on es  tablished paths to protect the grassland ecosystem. Do not litter and avoid picking wildflowers or disturbing local wildlife.",
      image:"images/uploads/kankoka 1.jpg",
    },
    {
      id:"cabantian-hills",
      name:"Cabantian Hills",
      category:"hills",
      municipality:"Guindulman",
      shortDescription:"A dramatic hilltop viewdeck in Guindulman with sweeping coastal and inland views — one of Bohol's best-kept scenic secrets.",
      fullDescription:"Cabantian Hills in Guindulman offers one of the most spectacular viewpoints in eastern Bohol, where rolling green hills meet the shimmering blue of the sea on the horizon. The elevated vantage point provides a stunning panorama of the surrounding municipalities, coconut groves, and coastline. The site is serene, unhurried, and largely undiscovered by mainstream tourism — making it ideal for those who appreciate natural beauty without the crowds. The short hike to the top is manageable and well worth every step.",
      howToGetThere:"From Tagbilaran, travel to Guindulman by bus or van (approximately 1.5 to 2 hours). From Guindulman town center, hire a habal-habal or tricycle toward Cabantian — ask locals for exact directions to the hilltop.",
      estimatedBudget:"₱300–₱800 per person",
      travelReminders:["Wear sturdy footwear for the trail","Bring sun protection and water","Early morning visits offer the clearest views","Ideal for small groups and photography"],
      sustainabilityNote:"Respect the natural landscape. Do not leave trash behind, avoid damaging vegetation, and be mindful of local residents in the area.",
      image:"images/uploads/cabantian.jpg",
    },
    {
      id:"alicia-panoramic-park",
      name:"Alicia Panoramic Park",
      category:"hills",
      municipality:"Alicia",
      shortDescription:"A peaceful hilltop park in Alicia with sweeping views of Bohol's lush countryside — a hidden gem for nature lovers.",
      fullDescription:"Alicia Panoramic Park is a tranquil elevated escape in the municipality of Alicia, offering commanding views of Bohol's scenic interior. The park sits atop a gentle hill surrounded by open greenery, making it an excellent spot for picnics, leisurely walks, and quiet contemplation. Unlike more commercialized viewpoints in Bohol, Alicia Panoramic Park retains a humble, community-managed character — complete with native-inspired rest areas and a calm atmosphere. Visitors are treated to panoramic vistas of forested hills and valley settlements that stretch toward the horizon.",
      howToGetThere:"From Tagbilaran, take a bus or van headed toward the eastern municipalities and alight at Alicia (approximately 1.5 hours). From the town proper, ask locals or hire a habal-habal to the park.",
      estimatedBudget:"₱200–₱600 per person",
      travelReminders:["Great for family outings and picnics","Bring your own food and water","Best visited in the morning for clear views","Entrance fee may apply — check with locals"],
      sustainabilityNote:"This park is community-managed. Dispose of waste properly, support local vendors inside the park, and respect the natural surroundings.",
      image:"images/uploads/alicia.jpg",
    },
    {
      id:"mount-sagungan",
      name:"Mount Sagungan",
      category:"hills",
      municipality:"Duero",
      shortDescription:"A rugged hillside adventure in Duero with untamed views of Bohol's eastern coast.",
      fullDescription:"Mount Sagungan in Duero is a rewarding trekking destination for those who love a bit of adventure with their scenery. Rising above the municipality's forested terrain, the mountain offers a challenging but satisfying climb through dense vegetation, open ridgelines, and rocky outcrops. At the summit, trekkers are rewarded with panoramic views of the surrounding mountains, the coastline of eastern Bohol, and the vast sea beyond. Far from any tourist infrastructure, Sagungan is a true hidden gem for hikers and nature enthusiasts looking for an authentic Bohol experience.",
      howToGetThere:"From Tagbilaran, travel to Duero by bus or van (approximately 2 hours). From the town center, arrange a local guide for the trek.",
      estimatedBudget:"₱800–₱3000 per person",
      travelReminders:["Hire a local guide — trails are unmarked","Start early morning to avoid midday heat","Bring ample water and high-energy snacks","Wear long sleeves and pants for the forest trail"],
      sustainabilityNote:"This is a pristine natural environment. Pack out all waste, do not cut or damage vegetation, and follow your guide's instructions to protect the ecosystem.",
      image:"images/uploads/sagungan 3.jpg",
    },
    {
      id:"himontagon-hills",
      name:"Himontagon Hills",
      category:"hills",
      municipality:"Loay",
      shortDescription:"A scenic hilltop escape in Loay with lush rolling views — Bohol's quiet answer to the Chocolate Hills.",
      fullDescription:"Himontagon Hills in Loay is a serene and largely undiscovered highland destination just a short distance from Tagbilaran City. The gently rolling hills are blanketed in green throughout the year, offering a quieter and more intimate alternative to the famous Chocolate Hills. The area is ideal for leisurely walks, nature photography, and simply soaking in the peaceful countryside atmosphere. Local families often visit on weekends for picnics and rest, giving the site a warm, community-centered character that feels genuinely Boholano.",
      howToGetThere:"From Tagbilaran, drive or take a tricycle to Loay (approximately 20–30 minutes). Ask locals for directions to Himontagon Hills — a short habal-habal ride from the town center.",
      estimatedBudget:"₱200–₱600 per person",
      travelReminders:["Best visited in the morning or late afternoon","Wear comfortable walking shoes","Bring water and snacks","Great for photography and quiet relaxation"],
      sustainabilityNote:"Help preserve the natural beauty of these hills. Do not litter, stay on existing paths, and support local residents and vendors in the area.",
      image:"images/uploads/himontagon.jpg",
    },

    // ===== HIDDEN RESTOS (5) =====
    {
      id:"the-canope",
      name:"The Canope",
      category:"hidden-restos",
      municipality:"Tagbilaran",
      shortDescription:"A moody, industrial-chic café built from repurposed shipping containers, hidden beneath a canopy of trees.",
      fullDescription:"The Canope is one of Tagbilaran's most unique dining destinations — a two-story café and hangout space constructed from black-painted shipping containers, nestled beneath towering trees. The lower deck is lined with warm wooden furniture and lush tropical plants, while the upper level offers an open-air roof deck with views of the surrounding greenery. The atmosphere is cool, laid-back, and just edgy enough to feel like a discovery. Perfect for coffee, casual meals, and long conversations.",
      howToGetThere:"Located in Tagbilaran City. Best reached by tricycle from the city center — ask for The Canope in Cogon area.",
      estimatedBudget:"₱200–₱600 per person",
      travelReminders:["Visit in the late afternoon for the best ambiance","Great for group hangouts and photoshoots","Check their social media for updated hours and menu"],
      sustainabilityNote:"Support this local business by dining in. Avoid single-use plastics and dispose of waste responsibly.",
      image:"images/uploads/canope 6.PNG",
    },
    {
      id:"painitan-sa-baybay",
      name:"Painitan Sa Baybay",
      category:"hidden-restos",
      municipality:"Jagna",
      shortDescription:"A rustic, open-air bamboo resto right on the sea — serving the classic Boholano breakfast of puto maya and sikwate.",
      fullDescription:"Painitan Sa Baybay is as authentic as it gets — a charming bamboo-and-nipa eatery built right at the water's edge, offering front-row views of the sparkling sea. The menu is simple and deeply Boholano: puto maya (sticky rice cakes) and sikwate (traditional hot chocolate), the ultimate local breakfast combination. With the sound of waves beneath you, salty sea breeze in the air, and the horizon stretched wide, this humble spot offers a dining experience that no fancy restaurant can replicate.",
      howToGetThere:"Located along the coastal road in Jagna. Take a bus from Dao Terminal to Jagna and ask for Painitan Sa Baybay — locals know it well.",
      estimatedBudget:"₱80–₱200 per person",
      travelReminders:["Best visited for breakfast or early morning snacks","Cash only","Arrive early — puto maya sells out fast!"],
      sustainabilityNote:"Support this small local business. Avoid leaving litter near the shoreline — the ocean is right at your table.",
      image:"images/uploads/baybay 2.jpg",
    },
    {
      id:"lami-resto-bar",
      name:"LaMi Resto Bar",
      category:"hidden-restos",
      municipality:"Tagbilaran",
      shortDescription:"A breezy bamboo nipa-hut resto bar where golden sunsets, fresh flowers, and good food come together beautifully.",
      fullDescription:"LaMi Resto Bar is a charming open-air dining experience that blends rustic Filipino aesthetics with a relaxed, garden-fresh vibe. Housed in a traditional bamboo and nipa structure, the second-level balcony offers a dreamy perch — draped with sheer curtains, adorned with fresh flowers, and bathed in warm afternoon sunlight filtering through the trees. The menu features Filipino comfort food and refreshing drinks, best enjoyed as the sun dips below the horizon. LaMi is a favorite for quiet dates, casual dinners, and anyone who wants to eat somewhere that feels like a hidden garden retreat.",
      howToGetThere:"Located in Tagbilaran City. Ask locals or check their Facebook page for the exact address. Easily reached by tricycle from the city center.",
      estimatedBudget:"₱200–₱600 per person",
      travelReminders:["Visit during late afternoon for the golden hour ambiance","Reservations recommended on weekends","Great for dates and small gatherings"],
      sustainabilityNote:"Support this locally owned resto. Choose sustainable menu options where available and dispose of waste properly.",
      image:"images/uploads/lami.jpg",
    },
    {
      id:"bnalot-de-bohol",
      name:"B'Nalot De Bohol",
      category:"hidden-restos",
      municipality:"Tagbilaran",
      shortDescription:"A traditional nipa hut dining village with a distinct taste of Bohol — rustic, authentic, and full of character.",
      fullDescription:"B'Nalot De Bohol brings the spirit of traditional Boholano dining to life through its charming cluster of authentic nipa and bamboo hut structures. Each cottage is a cozy, intimate dining space surrounded by lush greenery, creating an atmosphere that feels like eating in the provincial countryside even in the heart of town. The menu highlights local Boholano cuisine and comfort food, and the setting is a photographer's dream. It's the kind of place where the experience is just as delicious as the food.",
      howToGetThere:"Located in Tagbilaran City. Check their Facebook page or ask locals for the current location. Accessible by tricycle.",
      estimatedBudget:"₱200–₱700 per person",
      travelReminders:["Great for groups and family dining","Call ahead for reservations on busy days","Try the signature local dishes — they are worth it"],
      sustainabilityNote:"Choose locally sourced dishes to support Boholano farmers and producers. Dispose of waste responsibly and respect the natural surroundings.",
      image:"images/uploads/bnalot (3).JPG",
    },
    {
      id:"aftertaste-sizzling-bar",
      name:"Aftertaste Sizzling Bar",
      category:"hidden-restos",
      municipality:"Tagbilaran",
      shortDescription:"A magical garden resto under the moonlight — string lights, open skies, and sizzling good food.",
      fullDescription:"Aftertaste Sizzling Bar is one of Tagbilaran's most enchanting dining experiences, best enjoyed after dark. The sprawling garden space is strung with warm Edison bulbs that create a glowing, romantic atmosphere beneath the open night sky. Guests dine on rustic cement tables and wooden stools surrounded by flowers and greenery, with the moon often making a spectacular appearance above. The menu centers on sizzling Filipino favorites — bold flavors, hearty portions, and the satisfying sound of a hot plate delivered to your table. A night at Aftertaste is a full sensory experience.",
      howToGetThere:"Located in Tagbilaran City. Check their social media for the address. Best reached by tricycle.",
      estimatedBudget:"₱200–₱700 per person",
      travelReminders:["Best visited at night for the full ambiance","Great for groups and celebrations","Try the sizzling dishes — they are the house specialty"],
      sustainabilityNote:"Support this local garden resto. Avoid leaving waste in the outdoor space and respect the natural garden environment.",
      image:"images/uploads/after (3).jpg",
    },

  ];

  const categoryLabels = {
    beaches: { label: "Beaches", icon: "🏖️" },
    waterfalls: { label: "Waterfalls", icon: "💧" },
    hills: { label: "Hills", icon: "⛰️" },
    cultural: { label: "Cultural Sites", icon: "🏛️" },
    "hidden-restos": { label: "Hidden Restos", icon: "🍽️" }
  };

  const galleryData = {
    hills: {
      title: "Hills",
      images: [
        { src: "images/uploads/kankoka 2.jpg", alt: "Kankoka Hills Candijay" },
        { src: "images/uploads/cabantian 2.jpg", alt: "Cabantian Hills Guindulman" },
        { src: "images/uploads/alicia 2.jpg", alt: "Alicia Panoramic Park Alicia" },
        { src: "images/uploads/sagungan 2.jpg", alt: "Mount Sagungan Duero" },
        { src: "images/uploads/himontagon 2.jpg", alt: "Himontagon Hills Loay" }
      ]
    },
    beaches: {
      title: "Beaches",
      images: [
        { src: "images/uploads/quinale 2.PNG", alt: "Quinale Beach Anda" },
        { src: "images/uploads/momoo.png", alt: "Momo Beach Panglao" },
        { src: "images/uploads/doljoo.PNG", alt: "Doljo Beach Panglao" },
        { src: "images/uploads/bikinii.jpg", alt: "Bikini Beach aerial view" },
        { src: "images/uploads/sibukaw www.jpg", alt: "Sibukaw Beach Anda" }
      ]
    },
    "hidden-restos": {
      title: "Hidden Restos",
      images: [
        { src: "images/uploads/canope 6.PNG", alt: "The Canope container cafe" },
        { src: "images/uploads/baybay.jpg", alt: "Painitan Sa Baybay seaside" },
        { src: "images/uploads/lamii.JPG", alt: "LaMi Resto Bar balcony" },
        { src: "images/uploads/bnalott.JPG", alt: "B'Nalot De Bohol nipa huts" },
        { src: "images/uploads/aftertastee.jpg", alt: "Aftertaste Sizzling Bar at night" }
      ]
    },
    waterfalls: {
      title: "Waterfalls",
      images: [
        { src: "images/uploads/INGKUMHAN.jpg", alt: "Ingkumhan Falls Dimiao" },
        { src: "images/uploads/CAN UMM.jpg", alt: "Can-umantad Falls Candijay" },
        { src: "images/uploads/busaiii.jpg", alt: "Busai Dream Falls Loboc" },
        { src: "images/uploads/kawasannn.jpg", alt: "Kawasan Falls Trinidad" },
        { src: "images/uploads/malinginn.jpg", alt: "Malingin Falls Cortes" }
      ]
    },
    cultural: {
      title: "Cultural Sites",
      images: [
        { src: "images/uploads/bacs.jpg", alt: "Baclayon Ancestral Houses" },
        { src: "images/uploads/clarinn an.jpg", alt: "Clarin Ancestral House Loay" },
        { src: "images/uploads/baclayon-ecclesiastical.jpg", alt: "Baclayon Church Museum" },
        { src: "images/uploads/asinn.jpg", alt: "Asin Tibuok artisanal salt" },
        { src: "images/uploads/PUNTA CRUZZ.jpg", alt: "Punta Cruz Watchtower Maribojoc" }
      ]
    }
  };